name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: "!startsWith(github.event.head_commit.message, 'Update manifest version to')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract Tag Without `v`
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/} # Remove refs/tags/
          TAG_NAME=${TAG_NAME#v}            # Remove leading v if present
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Determine previous tag
        id: prevtag
        run: |
          # Sort tags by cration date and take 2nd top
          PREV_TAG=$(git tag --sort=-creatordate | sed -n '2p')
          echo "PREVIOUS_TAG=$PREV_TAG" >> $GITHUB_ENV
          echo "Previous tag is $PREV_TAG"

      - name: Update version
        run: |
          python3 .github/update_version.py --version $TAG_NAME

      - name: Commit version change
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add custom_components/**/manifest.json
          git commit -m "Update manifest version to $TAG_NAME" || echo "No changes"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:$GITHUB_REF_NAME

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.TAG_NAME }}
          previous_tag: ${{ env.PREVIOUS_TAG }}
          generate_release_notes: true
